#!/bin/bash

#INPUT=RAW/meas_MID00110_FID14256_SPEN_diff_post_4seg.dat
#INPUT=RAW/meas_MID00108_FID14254_SPEN_diff_post_3seg.dat
#IINPUT=RAW/meas_MID00106_FID14252_SPEN_diff_post_1seg.dat

#INPUT=/home/mygadg/Data/RAW/meas_MID00413_FID50937_mo_SPEN_diff_gadg_4scan_tr_b01000_1p2x1p2x2_pFT_0p75.dat
INPUT=/home/mygadg/Data/RAW/meas_MID00280_FID51527_mo_SPEN_diff_gadg_4scan_tr_b01000_1p2x1p2x2_no_pFT_192x192.dat

echo $INPUT

OUTPUT=$(echo ${INPUT} | sed "s/.dat/.h5/g")
echo $OUTPUT

OUTPUT_NOISE=$(echo ${OUTPUT} | sed "s/FID/NOISE/g") 
echo $OUTPUT_NOISE

rm ${OUTPUT_NOISE}
rm ${OUTPUT}

siemens_to_ismrmrd -m IsmrmrdParameterMap_Siemens_SPEN.xml -x IsmrmrdParameterMap_Siemens_SPEN.xsl -f ${INPUT} -o ${OUTPUT_NOISE} -z 1
siemens_to_ismrmrd -m IsmrmrdParameterMap_Siemens_SPEN.xml -x IsmrmrdParameterMap_Siemens_SPEN.xsl -f ${INPUT} -o ${OUTPUT} -z 2
#siemens_to_ismrmrd -m IsmrmrdParameterMap_Siemens_SPEN.xml -x IsmrmrdParameterMap_Siemens_SPEN.xsl -f ${INPUT} -o ${OUTPUT}

